### ISSUE TITLE
admin_footer_text is showing on all the pages and posts, instead of the plugin settings page

### ISSUE THREAD

**Issue by josevarghese** [nkb-bd/wp-debug-log-config-tool#2]
First thing first, thanks for the great plugin! I'm using your plugin on all my debug sites, saving me a lot of time.

However, today, I noticed that the `admin_footer_text` you added to the plugin is loading on all WordPress pages. So, it would be great if you set it to only show on the plugin settings page of "Debug Log—Manger Tool" instead of all WP pages. Also, your review text on the ` admin_footer_text` overrides the other plugins and themes settings page, confusing the users.

Thanks, and wishing you a great day!

**Comment by nkb-bd** [comment]
Thanks for using the plugin ,yes I will fix it

**Comment by nkb-bd** [comment]
Fixed
